const catchError = require('../utils/catchError');
const Degree  = require('../models/Degree');

const getAll = catchError(async(req, res) => {
    const results= await Degree.findAll()
    return res.json(results)
});
const create = catchError(async(req,res)=>{
    const result  = await Degree.create(req.body)
    return res.status(201).json(result);
})
const getOne = catchError(async(req,res)=>{
    const{ id }= req.params
    const result = await Degree.findByPk(id);
    if(!result) return  res.status(404).send();
    
    return res.json(result);
})
const remove = catchError(async(req,res)=>{
    const { id }=  req.params;
    const result= await Degree.destroy( {where: { id}});
    if(!result) return  res.status(404).send()
    return res.status(204).send()
})

const update= catchError(async(req,res)=>{
    const {id}=req.params
    const result=await Degree.update(req.body ,{ where : {id},returning:true });
    if(!result[0]===0) return res.sendStatus(404);
    return res.json(result[1][0])
});

module.exports = {
    getAll,
    create,
    getOne,
    remove,
    update
}